### ISSUE TITLE
Improve cycling routes and rider safety. Discourage car use.

### ISSUE THREAD

**Issue by pavsmith** [OpenEastleigh/eastleigh-manifesto#17]
Improve cycling routes around Eastleigh by improving cycling routes, cannibalising existing road space where necessary. Reducing overall traffic speeds via both changing maximum speeds and traffic management infrastructure. Discourage the use of cars by implementing a highly effective Park and Ride and cutting back on parking, especially free parking.

**Comment by jt-nti** [comment]
[Improve cycling routes](https://groupthink.openeastleigh.uk/proposals/16) is open and ready for comments!

**Comment by jt-nti** [comment]
This idea resulted in the first successful Eastleigh Manifesto proposal!
